server:
  port: 80
spring:
  application:
    name: cloud-consumer-order-feign
eureka:
  client:
     #是否将自己注册到注册中心, 默认true
    register-with-eureka: false
    #是否从EurekaServer抓取已有的注册信息,单机无所谓,集群必须设置为true配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #      defaultZone: http://localhost:7001/eureka  #单机版
      defaultZone: http://eureka7001:7001/eureka,http://eureka7002:7002/eureka, http://eureka7003:7003/eureka #集群版

#设置feign客户端超时时间(OpenFeign 默认支持ribbon)
ribbon:
  #指的是建立连接所用时间,适用于网络状况正常情况下,两端连接所用时间
  ReadTimeout: 5000
  #指的是连接建立后,从服务器获取到可用资源所用时间
  ConnectTimeout: 5000
#监听feign 日志
logging:
  level:
    com.telecom.springcloud.service: debug
