server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001
  client:
   # false 表示不向注册中心注册自己
    register-with-eureka: false
    #false 表示自己端就是注册中心 职责是维护实例 不需要检索
    fetch-registry: false
    service-url:
      #设置与Eureka Server 交互的地址查询服务和注册服务都需要依赖这个地址
      #defaultZone: http://eureka7002:7002/eureka/,http://eureka7003:7003/eureka/
      defaultZone: http://eureka7001:7001/eureka/
#  server:
#    #关闭自我保护机制 保证不可用服务被及时剔除
#    enable-self-preservation: false
#    #接收客户端发送心跳的间隔时间 eviction 驱逐
#    eviction-interval-timer-in-ms: 2000