server:
  port: 8001
spring:
  application:
    name: cloud-provider-hystrix-payment
#eureka配置
eureka:
  client:
    #表示将自己注册到Eureak Server 默认为true
    register-with-eureka: true
    #是否从EureakServer中抓取已有的注册信息 默认为true 单节点无所谓 集群必须设置为true，才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #单机版 Eureka
      defaultZone: http://eureka7001:7001/eureka
